### ISSUE TITLE
Build fails when building an executable project in a directory containing a space

### ISSUE THREAD

**Issue by matthewelse** [lancaster-university/microbit-targets#3] opened 2016-03-27 00:25 UTC
This is something I've only tested on Mac OS X, so this may be a problem specific to Mac OS X:

When building a project that is contained in a directory tree that includes a space (in my case, using bbc-microbit-classic-gcc) that produces an executable, the build fails at the link step due to the following line:

https://github.com/lancaster-university/microbit-targets/blob/master/bbc-microbit-classic-gcc/CMake/toolchain.cmake#L22

As a work around, you can change this line to:

```
string(REPLACE " " "\\ " SAFE_CMAKE_CURRENT_LIST_DIR ${CMAKE_CURRENT_LIST_DIR})
set(CMAKE_EXE_LINKER_FLAGS_INIT    "${CMAKE_EXE_LINKER_FLAGS_INIT} -mcpu=cortex-m0 -mthumb -T${SAFE_CMAKE_CURRENT_LIST_DIR}/../ld/NRF51822.ld")
```

As I said, this is untested on other platforms, but it seems to do the trick on OS X.

**Comment by adamboardman** [comment] 2016-08-05 11:24
I raised a duplicate of this bug in the wrong project, which has now been fixed by @jamesadevine: https://github.com/lancaster-university/microbit-targets/commit/09cf98ea0c05a5be49435cc6ad15727caeeaee62

**Comment by jamesadevine** [comment] 2016-08-05 11:48
Thanks @adamboardman, closing!

**Closed as completed by jamesadevine** 2016-08-05 11:48 UTC
